class CreateCharacteristicsService
  def call
    Characteristic.create name: "A estrenar", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Balcón", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Comedor", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Dormitorio en suite", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Baulera", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Comedor diario", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Escritorio", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Cocina", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Dependencia servicio", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Hall", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Jardin", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Lavadero", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Living", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Living Comedor", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Patio", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Terraza", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Servicios", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Agua Corriente", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Desagüe cloacal", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Video cable", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Gas Natural", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Internet", characteristic_type: "CharacteristicInstance::Boolean"
    Characteristic.create name: "Pavimento", characteristic_type: "CharacteristicInstance::Boolean"

    Characteristic.create name: "Superficie total(m2)", characteristic_type: "CharacteristicInstance::Integer"
    Characteristic.create name: "Superficie Cubierta (m2)", characteristic_type: "CharacteristicInstance::Integer"
    Characteristic.create name: "Cantidad de hambientes", characteristic_type: "CharacteristicInstance::Integer"
    Characteristic.create name: "Expensas aproximadas", characteristic_type: "CharacteristicInstance::Integer"
    Characteristic.create name: "Antiguedad", characteristic_type: "CharacteristicInstance::Integer"
    Characteristic.create name: "Baños", characteristic_type: "CharacteristicInstance::Integer"

    Characteristic.create name: "Calle", characteristic_type: "CharacteristicInstance::String"
    Characteristic.create name: "Altura", characteristic_type: "CharacteristicInstance::String"
    Characteristic.create name: "Barrio", characteristic_type: "CharacteristicInstance::String"
  end
end
